// an intent makes a change in the game world
//   these are generated by actors in the simulation, say Gods, Populations, etc.
trait Intent:
  def createdById : String                    // id of entity generating intent
  def cost        : Int                       // action point cost of intent
  def applyTo(state: WorldState): WorldState  // apply the intent to the game world
